### PR TITLE
added shorthand support

### PR DESCRIPTION
**Pull request by carlj**
Hi,

i recently added the shorthand support, that we discussed in https://github.com/premosystems/XCAsyncTestCase/issues/5 . I chose the `XAT_` prefix, but im not quite sure if this prefix is the best.

Just let me know if you have any changes.
Cheers

### CODE REVIEW

**Comment by vincilbishop** [comment]
I would change it to XC

From:  Carl Jahn notifications@github.com
Reply-To:  premosystems/XCAsyncTestCase
<reply+i-35691036-402131395d90a464f8d57a4ece9d555f7a6db265-775848@reply.gith
ub.com>
Date:  Friday, June 13, 2014 at 12:29 PM
To:  premosystems/XCAsyncTestCase XCAsyncTestCase@noreply.github.com
Subject:  [XCAsyncTestCase] added shorthand support (#9)

Hi,

i recently added the shorthand support, that we discussed in #5
https://github.com/premosystems/XCAsyncTestCase/issues/5  . I chose the
XAT_ prefix, but im not quite sure if this prefix is the best.

Just let me know if you have any changes.
Cheers

You can merge this Pull Request by running
  git pull https://github.com/carlj/XCAsyncTestCase master
Or view, comment on, or merge it at:

  https://github.com/premosystems/XCAsyncTestCase/pull/9
Commit Summary
- added shorthand support
  File Changes
-  M AsyncXCTestingKit/AsyncXCTestingKit/AsyncXCTestingKit-Prefix.pch
  https://github.com/premosystems/XCAsyncTestCase/pull/9/files#diff-0  (4)
-  M AsyncXCTestingKit/AsyncXCTestingKit/XCTestCase+AsyncTesting.h
  https://github.com/premosystems/XCAsyncTestCase/pull/9/files#diff-1  (20)
-  M AsyncXCTestingKit/AsyncXCTestingKit/XCTestCase+AsyncTesting.m
  https://github.com/premosystems/XCAsyncTestCase/pull/9/files#diff-2  (197)
-  M AsyncXCTestingKit/AsyncXCTestingKitTests/AsyncXCTestingKitTests.m
  https://github.com/premosystems/XCAsyncTestCase/pull/9/files#diff-3  (2)
  Patch Links:
- https://github.com/premosystems/XCAsyncTestCase/pull/9.patch
- https://github.com/premosystems/XCAsyncTestCase/pull/9.diff
  ‹
  Reply to this email directly or view it on GitHub
  https://github.com/premosystems/XCAsyncTestCase/pull/9 .

**Comment by carlj** [comment]
but we should use a 3 letter prefix, [as recommended](https://developer.apple.com/library/ios/documentation/cocoa/conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html).

> Your own classes should use three letter prefixes. These might relate to a combination of your company name and your app name, or even a specific component within your app. As an example, if your company were called Whispering Oak, and you were developing a game called Zebra Surprise, you might choose WZS or WOZ as your class prefix

Maybe `XCA` ?

**Comment by vincilbishop** [comment]
So would that be XCA?

From:  Carl Jahn notifications@github.com
Reply-To:  premosystems/XCAsyncTestCase
<reply+i-35691036-402131395d90a464f8d57a4ece9d555f7a6db265-775848@reply.gith
ub.com>
Date:  Friday, June 13, 2014 at 12:47 PM
To:  premosystems/XCAsyncTestCase XCAsyncTestCase@noreply.github.com
Cc:  Vincil Bishop info@premosystems.com
Subject:  Re: [XCAsyncTestCase] added shorthand support (#9)

but we should use a 3 letter prefix, as recommended
<https://developer.apple.com/library/ios/documentation/cocoa/conceptual/Prog
rammingWithObjectiveC/Conventions/Conventions.html> .

> Your own classes should use three letter prefixes. These might relate to a
> combination of your company name and your app name, or even a specific
> component within your app. As an example, if your company were called
> Whispering Oak, and you were developing a game called Zebra Surprise, you
> might choose WZS or WOZ as your class prefix

‹
Reply to this email directly or view it on GitHub
<https://github.com/premosystems/XCAsyncTestCase/pull/9#issuecomment-4604004
4> .

**Comment by carlj** [comment]
sure, `XCA` would be the best. 

done -> https://github.com/carlj/XCAsyncTestCase/commit/dc8d0badccdcf629fbbe36fe4d1371558de99976

**Comment by carlj** [comment]
@premosystems would you like to merge the changes?

**Comment by vincilbishop** [comment]
Wow, looks good. Thanks for taking the time to do those changes.

It looks like it will be shorthand by default...so that is a good thing.

One question...just by reading the code it seems like it will always be shorthand. Have you tested turning shorthand on/off? How would you do that?

**Comment by carlj** [comment]
sry, i forgot to mention that the shorthand isn't active by default, because i used the same approach as MagicalRecord did. 

The problem: It is easier to define the `XCA_SHORTHAND` than to undefined it when it is already defined in the `XCTestCase+AsyncTesting.h` file

To turn the shorthand on just post the following in your `...-prefix.pch`file

```
#ifndef XCA_SHORTHAND
#define XCA_SHORTHAND
#endif
```

**Comment by vincilbishop** [comment]
Ah ok...I thought you were going to expose something I didn't know about preprocessor macros, hahaha...

So let's do this in order to not break previous implementations. Let's make shorthand the default. Change the preprocessor macro to XCA_METHOD_PREFIXES. If that preprocessor macro is defined then XCA_ must be prepended to call methods. normal methods signatures are not visible to avoid conflicts.

I think you can achieve that by reversing what you have done.

I know that MR does the opposite, but I have never agreed with that approach. I just like giving the option for method prefixes in case there is a conflict. in 99.999% of all cases there won't be a conflict, so why should we impose an additional complexity on every consumer for something that probably doesn't affect them?

Let me know what you think. Main thing is I don't think it's a good idea to break previous implementations.

**Comment by Dinkh** [comment]
@carlj approach is fine with me. Works great.

**Comment by grigaci** [comment]
I would also go with the shorthand off by default. 
It's something that I expect to have. It would be confusing to have some libs(such as MagicalRecord) with shorthand set to off and other libs with it set to on(such as this one).

**Comment by anwittmann** [comment]
@carlj  i would also support your solutions. shorthand should always be off by default imo.

**Comment by carlj** [comment]
@duemunk what is your opinion? should we activate or disable the shorthand by default?

**Comment by duemunk** [comment]
Great work guys! I'm glad to see this being implemented, no matter if it's on or off by default.

The only reason for keeping it off by default is IMHO due to backwards compatibility. 
It is much easier to debug, knowing that confusion of code doesn't happen and that no swizzling is involved in the process. 

So basically I'm advocating for having no option at all – code should just be prefixed :) It makes me much more likely to use a library if they use prefixes, and even better if it's without the need of any swizzling to make it happen.

**Comment by vincilbishop** [comment]
I agree @duemunk, well put.

The only thing that holds me back is breaking backwards compatibility. 

Maybe it's time to just rev the podspec version to 1.0 and make an announcement that the API has changed.

Seems like there is a consensus for shorthand off by default...

Again, thanks @carlj for taking the time to code this up and entertain our rants on software :)

**Pull request merged**
